import { lazy } from "react";

const routes = [
  {
    path: "/login",
    is_public: true,
    component: lazy(() => import("./Login")),
    layout: "auth",
    title: "Login",
  },
  {
    path: "/signup",
    is_public: true,
    component: lazy(() => import("./Register")),
    layout: "auth",
    title: "Register",
  },
  {
    path: "/success",
    is_public: true,
    component: lazy(() => import("./Success")),
    layout: "auth",
    title: "Success",
  },
  {
    path: "/",
    is_public: true,
    component: lazy(() => import("./Home")),
    layout: "app",
    title: "Home",
  },
  {
    path: "/:category/:id",
    is_public: true,
    component: lazy(() => import("./Categories")),
    layout: "app",
    title: "Home",
    is_breadcrumb: true,
  },
  {
    path: "/product/:slug",
    is_public: true,
    component: lazy(() => import("./ProductDetail")),
    layout: "sub",
    title: "Home",
    is_breadcrumb: true,
  },
  {
    path: "/checkout/cart",
    is_public: false,
    component: lazy(() => import("./Carts")),
    layout: "sub",
    title: "Home",
    is_breadcrumb: false,
  },
  {
    path: "/checkout/shipping",
    is_public: false,
    component: lazy(() => import("./Address")),
    layout: "sub",
    title: "Home",
    is_breadcrumb: false,
  },
  {
    path: "/checkout/payment",
    is_public: false,
    component: lazy(() => import("./Checkout")),
    layout: "sub",
    title: "Home",
    is_breadcrumb: false,
  },
  {
    path: "/sale/order/history",
    is_public: false,
    component: lazy(() => import("./Orders")),
    layout: "sub",
    title: "Home",
    is_breadcrumb: false,
  },
  {
    path: "/sale/order/view/:id",
    is_public: false,
    component: lazy(() => import("./OrderView")),
    layout: "sub",
    title: "Home",
    is_breadcrumb: false,
  },
  {
    path: "/customer/account/edit",
    is_public: false,
    component: lazy(() => import("./Profile")),
    layout: "sub",
    title: "Home",
    is_breadcrumb: false,
  },
  {
    path: "*",
    is_public: true,
    component: lazy(() => import("./PageNotFound")),
    layout: "auth",
    title: "Home",
  },
];

export default routes;
